substitutions:
  device_name: "horror-haus"  # only lowercase, numbers, - and _ allowed!
  friendly_name: "Horror-Haus"
  local_domain: ".fritz.box"


esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  
  on_boot:
    - priority: -100
      then:
        - dfplayer.set_volume:
            volume: !lambda "return (int) round(id(volume).state * 30.0 / 100.0);"

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption

  actions:
    # Play file from /mp3/xxxx.mp3
    - action: play_mp3
      variables:
        file: int
      then:
        - dfplayer.play_mp3:
            file: !lambda "return file;"
    # Play file from numbered folder, e.g. /01/001.mp3
    - action: play_folder
      variables:
        folder: int
        file: int
      then:
        - dfplayer.play_folder:
            folder: !lambda "return folder;"
            file: !lambda "return file;"
    # Set DFPlayer volume directly (0-30)
    - action: set_volume
      variables:
        value: int
      then:
        - dfplayer.set_volume:
            volume: !lambda "return value;"
    # Control light partitions of WS2812B RGB LED Strip using bitmask
    # 0 = all off
    # bit 0 = led_door
    # bit 1 = led_bay_1
    # bit 2 = led_small_window
    # bit 3 = led_bay_2
    # bit 4 = led_roof_1
    # bit 5 = led_roof_2
    # brightness in %
    # red&green/blue in 0-255
    - action: partition_light
      variables:
        partition_bits: int
        brightness: float
        red: float
        green: float
        blue: float
      then:
        - script.execute:
            id: partition_light
            partition_bits: !lambda "return partition_bits;"
            brightness: !lambda "return brightness;"
            red: !lambda "return red;"
            green: !lambda "return green;"
            blue: !lambda "return blue;"

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_wohnzimmer_ssid
    password: !secret wifi_wohnzimmer_password

  domain: "${local_domain}"
  use_address: 192.168.178.169

  output_power: 14dB   # https://esphome.io/guides/faq/#brownout-detector-was-triggered
  
  ap:
    ssid: "${device_name} Hotspot"
    password: !secret hotspot_password

captive_portal:


uart:
  - id: dfplayer_uart
    tx_pin: GPIO3
    rx_pin: GPIO1
    baud_rate: 9600
  - id: uart_ld2410
    tx_pin: GPIO17
    rx_pin: GPIO16
    parity: NONE
    stop_bits: 1
    baud_rate: 256000

dfplayer:
  uart_id: dfplayer_uart
  id: my_dfplayer

number:
  - platform: template
    name: "Volume"
    id: volume
    icon: mdi:volume-high
    unit_of_measurement: "%"
    min_value: 0
    max_value: 100
    step: 1
    restore_value: true
    initial_value: 50

    set_action:
      - dfplayer.set_volume:
          volume: !lambda "return (int) round(x * 30.0 / 100.0);"

button:
  - platform: template
    name: "Zufallswiedergabe"
    disabled_by_default: true
    icon: mdi:play
    on_press:
      - dfplayer.random

  - platform: template
    name: "Wiedergabe stoppen"
    disabled_by_default: true
    icon: mdi:stop
    on_press:
      - dfplayer.stop


packages:
  - !include lights.yaml

select:
  - platform: template
    name: "Power-LED Effekt"
    id: power_led_effect
    icon: mdi:lightbulb-auto
    optimistic: true
    options:
      - "Aus"
      - "Kerzenflackern"
      - "Blitz"
    on_value:
      - if:
          condition:
            lambda: 'return i == 0;'
          then:
            - light.turn_off: power_led_1
            - light.turn_off: power_led_2
            - light.turn_off: power_led_3
            - light.turn_off: power_led_4
            - light.turn_off: power_led_5
      - if:
          condition:
            lambda: 'return i == 1;'
          then:

            - light.turn_on:
                id: power_led_1
                effect: flicker
                brightness: 35%
            - light.turn_on:
                id: power_led_2
                effect: flicker
                brightness: 35%
            - light.turn_on:
                id: power_led_3
                effect: flicker
                brightness: 35%
            - light.turn_on:
                id: power_led_4
                effect: flicker
                brightness: 35%
            - light.turn_on:
                id: power_led_5
                effect: flicker
                brightness: 35%
      - if:
          condition:
            lambda: 'return i == 2;'
          then:
            - light.turn_on:
                id: power_led_1
                effect: flash
            - delay: 100ms
            - light.turn_on:
                id: power_led_2
                effect: flash
            - delay: 100ms
            - light.turn_on:
                id: power_led_3
                effect: flash
            - delay: 100ms
            - light.turn_on:
                id: power_led_4
                effect: flash
            - delay: 100ms
            - light.turn_on:
                id: power_led_5
                effect: flash
            - delay: 100ms
            - select.first: power_led_effect



ld2410:
  uart_id: uart_ld2410

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true


binary_sensor:
  - platform: status
    name: "Status"

  - platform: ld2410
    has_target:
      name: "Anwesenheit"
      filters:
        - delayed_on: 200ms
        - delayed_off: 2s

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    icon: mdi:wifi

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal %"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    icon: mdi:wifi

  - platform: ld2410
    detection_distance:
      name: "Bewegungserkennung Abstand"
      id: ld2410_distance
      filters:
        - throttle: 30s

  - platform: bh1750
    name: "Umgebungshelligkeit"
    id: ambient_light
    address: 0x23
    update_interval: 30s

